//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetManagamentService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_Project_Details
    {
        public int id { get; set; }
        public Nullable<int> Manager_Id { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<bool> Allocation_Status { get; set; }
        public Nullable<int> Bill_Id { get; set; }
        public Nullable<System.DateTime> created_Date { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
    
        public virtual Employee_Manager Employee_Manager { get; set; }
        public virtual Project_Details Project_Details { get; set; }
    }
}
