//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetManagementApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Project_Details
    {
        public int id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public Nullable<int> Geo_Id { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<bool> Allocation_Status { get; set; }
        public Nullable<System.DateTime> created_Date { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
    
        public virtual Employee_Details Employee_Details { get; set; }
        public virtual Project_Details Project_Details { get; set; }
        public virtual Geo_Location Geo_Location { get; set; }
    }
}
