//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetManagementApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Task_Details
    {
        public int Employee_Task_Id { get; set; }
        public Nullable<int> TimeSheet_Id { get; set; }
        public Nullable<int> Task_Id { get; set; }
        public Nullable<int> Employee_Hours { get; set; }
        public Nullable<System.DateTime> created_Date { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
    
        public virtual Task_Type Task_Type { get; set; }
        public virtual TimeSheet TimeSheet { get; set; }
    }
}
