//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetManagementApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_Approval
    {
        public int Approval_ID { get; set; }
        public Nullable<int> TimeSheet_Id { get; set; }
        public Nullable<int> Manager_Id { get; set; }
        public Nullable<System.DateTime> Submission_Date { get; set; }
        public Nullable<bool> Is_Approved { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
    
        public virtual Employee_Manager Employee_Manager { get; set; }
        public virtual TimeSheet TimeSheet { get; set; }
    }
}
