//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetManagementApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeSheetManagementEntities : DbContext
    {
        public TimeSheetManagementEntities()
            : base("name=TimeSheetManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Employee_Details> Employee_Details { get; set; }
        public virtual DbSet<Employee_Leaves> Employee_Leaves { get; set; }
        public virtual DbSet<Employee_Manager> Employee_Manager { get; set; }
        public virtual DbSet<Employee_Project_Details> Employee_Project_Details { get; set; }
        public virtual DbSet<Employee_Task_Details> Employee_Task_Details { get; set; }
        public virtual DbSet<Geo_Location> Geo_Location { get; set; }
        public virtual DbSet<Holiday_Calender> Holiday_Calender { get; set; }
        public virtual DbSet<Leaves_Type> Leaves_Type { get; set; }
        public virtual DbSet<Manager_Approval> Manager_Approval { get; set; }
        public virtual DbSet<Manager_Project_Details> Manager_Project_Details { get; set; }
        public virtual DbSet<Project_Details> Project_Details { get; set; }
        public virtual DbSet<Task_Type> Task_Type { get; set; }
        public virtual DbSet<Time_Period> Time_Period { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
    }
}
