//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetManagementApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeSheet()
        {
            this.Employee_Task_Details = new HashSet<Employee_Task_Details>();
            this.Manager_Approval = new HashSet<Manager_Approval>();
        }
    
        public int TimeSheet_Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public Nullable<int> Working_Hours { get; set; }
        public Nullable<int> OverTime { get; set; }
        public Nullable<int> Leave_Id { get; set; }
        public Nullable<System.DateTime> created_Date { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
    
        public virtual Employee_Leaves Employee_Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Task_Details> Employee_Task_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager_Approval> Manager_Approval { get; set; }
    }
}
